apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
      id: controller-1
  template:
    metadata:
      labels:
        app: controller
        id: controller-1
    spec:
      containers:
        - name: controller-1
          image: apache/kafka:latest
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "controller"
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: controller-1
spec:
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: controller
    id: controller-1
