apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
      id: broker-1
  template:
    metadata:
      labels:
        app: broker
        id: broker-1
    spec:
      containers:
        - name: broker-1
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 19092
          env:
            - name: KAFKA_NODE_ID
              value: "4"
            - name: KAFKA_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: broker-1
spec:
  ports:
    - port: 9092
      targetPort: 9092
    - port: 19092
      targetPort: 19092
  selector:
    app: broker
    id: broker-1
